<?php

/**
 * @file
 * Allows the admin to enter complex logic for the emails that they send in 
 * respose to a webform.
 */

/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path
 *   Path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function webform_email_customizer_help($path, $arg) {
  switch ($path) {
    case "admin/help#webform_email_customizer":
      return '<p>'.t("Allows the admin to enter logic for webform ".
                     "response emails").'</p>';
      break;
  }
}

/**
 * Implements hook_menu().
 */
function webform_email_customizer_menu() {
  $items = array();

  // config
  $items['admin/config/webform_email_customizer_form'] = array(
    'title' => 'Webform email customizer configuration',
    'description' => 'Configuration for webform email customizer module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webform_email_customizer_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Form function, called by drupal_get_form() in 
 * webform_email_customizer_menu().
 * Allows an administrator to specify the custom logic underlying emails.
 */
function webform_email_customizer_form($form, &$form_state) {
  $form['webform_email_customizer_custom_emails'] = array(
    '#type' => 'textarea',
    '#title' => t('JSON for the emails and conditions.'),
    '#default_value' => variable_get('webform_email_customizer_custom_emails', 
                                     ''),
    '#size' => 30,
    # @todo DESCRIPTION OF THE JSON FORMAT
    '#description' => t('If you have a landing page that should set a '.
                        'variable, specify the page and then the query string '.
                        'with values that you want to set.  One landing page '.
                        'per line.  Path must be lowercase. For instance, to '.
                        'set the edit[submitted][company] field to MyCompany '.
                        'when landing on the /mycompany page, enter the '.
                        'following line: mycompany '.
                        'edit[submitted][company]=MyCompany'),
  );

  return system_settings_form($form);
}

